name: fr2 a02

on:
  schedule:
    - cron: '38 */5 * * *'  # Actualise toutes les 4 heures
  workflow_dispatch:       # Permet le déclenchement manuel

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Référentiel d’extraction
        uses: actions/checkout@v4

     # - name: Créer un dossier a02
     #   run: mkdir -p a02

      - name: Récupère le flux de fr2
        run: |
          source=$(curl -s -H "User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1" https://hdfauth.ftven.fr/esi/TA?url=https://simulcast-p.ftven.fr/simulcast/France_2/hls_fr2/index.m3u8)
          base=$(curl -e "https://www.france.tv/" -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" "$source")
          mu=$(echo $source | grep -oP "[^\n\r]*index")
          echo "$base" > a02/fr2.m3u8 | sed -i -e "s|France|$mu|g" -e "s|index|France|g" -e '4d' a02/fr2.m3u8



      - name: Construit les flux nationaux de FranceTV
        run: |
          #sed "s/France_Info\/hls_monde_frinfo\/France_Info/France_2\/hls_fr2\/France_2/g" a02/frinfo.m3u8 > a02/fr2.m3u8
          sed "s/France_Info\/hls_monde_frinfo\/France_Info/France_3\/hls_fr3\/France_3/g" a02/frinfo.m3u8 > a02/fr3.m3u8
          sed "s/France_Info\/hls_monde_frinfo\/France_Info/France_4\/hls_fr4\/France_4/g" a02/frinfo.m3u8 > a02/fr4.m3u8
          sed "s/France_Info\/hls_monde_frinfo\/France_Info/France_5\/hls_fr5\/France_5/g" a02/frinfo.m3u8 > a02/fr5.m3u8
          
      - name: Construit les flux régionaux de FranceTV
        run: |
          sed "s/France_Info\/hls_monde_frinfo\/France_Info/Regions_noa\/hls_noa\/Regions_noa/g" a02/frinfo.m3u8 > a02/frnoa.m3u8
          
      - name: Vérifie l'adresse IP de github
        run: |
          github_ip=$(curl https://api.ipify.org)
          echo "L'adresse IP de github est: $github_ip" > githubip.data        

      - name: Valide et transmet les modifications
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add -A
          ls -la 
          git commit -m "Dernière actualisation" # github.com/BG47510
          git push
